import time
# GRAPHICS
calcTop = "+-----------------+\n"
calcBlank = "|                 |\n"
calcScr = "| +-------------+ |\n"
calcButnR0 = "| (C)         (%) |\n"
calcButnR1 = "| (7) (8) (9) (+) |\n"
calcButnR2 = "| (4) (5) (6) (-) |\n"
calcButnR3 = "| (1) (2) (3) (X) |\n"
# EVERYTHING ELSE
menuCalc1 = "What do you want to do?\n" + "---------------\n" + "\n1. Addition" + "\n2. Subtraction" + "\n3. Multiplication" + "\n4. Division"
menuCalc2 = "Calculator Menu\n" + "---------------\n" + "\n1. Calculate" + "\n2. Close Program"
calcVal1 = "Please input the first value: "
calcVal2 = "Please input the second value: "
op = "\nPlease choose an option: "
calcClose = "\nNow closing..."
error = "Either that's not a number or something broke."
error2 = "Invalid option."
valueA = "Addition\n"
valueS = "Subtraction\n"
valueM = "Multiplication\n"
valueD = "Divison\n"
valueOutput = "Output\n"
empty = "--------------\n"
divZeroError = "Please don't divide by zero."
valueE = "ERROR\n"
