import time
# GRAPHICS
calcTop = "calcTop\n"
calcBlank = "calcBlank\n"
calcScr = "calcScr\n"
calcButnR0 = "calcButnR0\n"
calcButnR1 = "calcButnR1\n"
calcButnR2 = "calcButnR2\n"
calcButnR3 = "calcButnR3\n"
# EVERYTHING ELSE
menuCalc1 = "menuCalc1\n"
menuCalc2 = "menuCalc2\n"
calcVal1 = "calcVal1"
calcVal2 = "calcVal2"
op = "\nop"
calcClose = "\ncalcClose"
error = "error"
error2 = "error2"
valueA = "valueA\n"
valueS = "valueS\n"
valueM = "valueM\n"
valueD = "valueD\n"
valueOutput = "valueOutput\n"
empty = "empty\n"
divZeroError = "divZeroError"
valueE = "valueE\n"
